#!/usr/bin/env python3
"""
Layer 2 helper — search-pack generator (not a GitHub list scraper).

Default: emit data/agent_findings/_search_pack_<ts>.md with ready-to-open
Indeed / Google / ATS search URLs from data/discovery_queries.yml.
LinkedIn is optional and skipped on Cloud Automations.

Optional: --scan-extra-ats probes boards listed under extra_ats that are NOT
already in data/companies.yml (Layer 1). Never fetches Simplify/GitHub lists.

Cursor agents should follow docs/DISCOVERY_WORKFLOW.md, browse those URLs,
resolve official apply links, and write data/agent_findings/<ts>.json.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote_plus

import httpx
import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

QUERIES_PATH = ROOT / "data" / "discovery_queries.yml"
COMPANIES_PATH = ROOT / "data" / "companies.yml"
OUT_DIR = ROOT / "data" / "agent_findings"
USER_AGENT = "W27-SWE-Internships/1.0 (+agent-discover)"

WINTER_RE = re.compile(
    r"winter\s*2027|spring\s*2027|jan(?:uary)?\s*2027|"
    r"jan(?:uary)?\s*[-–/]\s*(?:apr(?:il)?|may)\s*2027",
    re.I,
)
INTERN_RE = re.compile(r"\b(intern|co-?op|co op)\b", re.I)
SWE_RE = re.compile(
    r"software|engineer|developer|full.?stack|backend|frontend|platform|"
    r"infra|swe|devops|sre|machine learning|ml engineer|data engineer",
    re.I,
)


def _load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _layer1_tokens(companies: dict) -> set[str]:
    tokens: set[str] = set()
    for c in companies.get("companies") or []:
        url = (c.get("board_url") or "").rstrip("/")
        if "/boards/" in url and "/jobs" in url:
            # .../boards/{token}/jobs
            parts = url.split("/")
            try:
                i = parts.index("boards")
                tokens.add(parts[i + 1].lower())
            except (ValueError, IndexError):
                pass
        elif "ashbyhq.com/posting-api/job-board/" in url:
            tokens.add(url.split("job-board/")[-1].split("?")[0].lower())
        elif "api.lever.co/v0/postings/" in url:
            tokens.add(url.split("postings/")[-1].split("?")[0].lower())
        name = (c.get("name") or "").strip().lower()
        if name:
            tokens.add(name.replace(" ", ""))
    return tokens


def write_search_pack(cfg: dict, ts: str) -> Path:
    exact = cfg.get("exact_queries") or cfg.get("queries") or []
    ats_qs = cfg.get("ats_queries") or []
    templates = cfg.get("search_url_templates") or {}
    ats_templates = cfg.get("ats_search_templates") or {}
    checklist = cfg.get("portal_checklist") or {}
    required = checklist.get("required") or []
    optional = checklist.get("optional") or []

    lines = [
        f"# W27 discovery search pack ({ts})",
        "",
        "Generated by `scripts/agent_discover.py`. Follow `docs/DISCOVERY_WORKFLOW.md`.",
        "",
        "## Mandatory portal checklist (every run)",
        "",
        "Complete **required** channels before finishing Layer 2. Skip LinkedIn on Cloud Automations.",
        "",
    ]
    for name in required:
        lines.append(
            f"- [ ] **{name}** — open ≥3 searches from this pack; resolve official apply URLs"
        )
    for name in optional:
        if name == "linkedin_jobs":
            lines.append(
                f"- [ ] **{name}** (optional) — **skip on Cloud Automations** (login almost always blocks). "
                "Use Indeed + ATS search instead."
            )
        else:
            lines.append(
                f"- [ ] **{name}** (optional) — try; if SSO/captcha, note `portals_blocked` and continue"
            )
    lines.extend(
        [
            "",
            "Rules:",
            "- **Required:** Indeed + ATS site search (Google or DuckDuckGo).",
            "- **Skip LinkedIn** on Cloud Agents — do not waste the run fighting login.",
            "- Persist **official apply** URLs only (Greenhouse / Lever / Ashby / Workday / Rippling).",
            "- Never store LinkedIn/Indeed/Handshake as `official_url`.",
            "- Write `data/agent_findings/<timestamp>.json` including `portals_attempted`, then ingest.",
            "",
            "---",
            "",
            "## Exact keyword searches",
            "",
        ]
    )

    # Primary portals for Cloud Automations (LinkedIn/Handshake optional, listed last)
    primary_portals = ["indeed", "google"]
    optional_portals = ["linkedin_jobs", "handshake"]
    for q in exact:
        lines.append(f"### {q}")
        lines.append("")
        encoded = quote_plus(q)
        for name in primary_portals:
            tmpl = templates.get(name)
            if not tmpl:
                continue
            lines.append(f"- **{name}**: {tmpl.replace('{q}', encoded)}")
        for name in optional_portals:
            tmpl = templates.get(name)
            if not tmpl:
                continue
            lines.append(f"- **{name}** (optional / skip on Cloud): {tmpl.replace('{q}', encoded)}")
        lines.append("")

    lines.extend(["---", "", "## ATS site searches (Google / DuckDuckGo)", ""])
    for q in ats_qs:
        lines.append(f"### {q}")
        lines.append("")
        encoded = quote_plus(q)
        for name, tmpl in ats_templates.items():
            lines.append(f"- **{name}**: {tmpl.replace('{q}', encoded)}")
        lines.append("")

    path = OUT_DIR / f"_search_pack_{ts}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _winter_blob(*parts: str) -> bool:
    return bool(WINTER_RE.search(" ".join(parts)))


def from_greenhouse(client: httpx.Client, token: str, company: str) -> list[dict]:
    url = f"https://boards-api.greenhouse.io/v1/boards/{token}/jobs"
    data = client.get(url).json()
    out = []
    for item in data.get("jobs") or []:
        title = item.get("title") or ""
        loc = (item.get("location") or {}).get("name") or ""
        if not INTERN_RE.search(title) or not SWE_RE.search(title):
            continue
        if not _winter_blob(title, loc):
            continue
        apply = item.get("absolute_url") or ""
        if not apply:
            continue
        out.append(
            {
                "company": company,
                "exact_role_title": title,
                "location": loc,
                "term": "Winter 2027",
                "official_url": apply,
                "posting_date": None,
                "notes": f"extra_ats greenhouse:{token}",
            }
        )
    return out


def from_ashby(client: httpx.Client, token: str, company: str) -> list[dict]:
    url = f"https://api.ashbyhq.com/posting-api/job-board/{token}"
    resp = client.get(url)
    if resp.status_code != 200:
        return []
    out = []
    for item in resp.json().get("jobs") or []:
        title = item.get("title") or ""
        loc = item.get("location") or ""
        if isinstance(loc, dict):
            loc = loc.get("name") or ""
        desc = (item.get("descriptionPlain") or "")[:4000]
        if not INTERN_RE.search(title):
            continue
        if not SWE_RE.search(f"{title} {desc}"):
            continue
        if not _winter_blob(title, str(loc), desc):
            continue
        apply = item.get("jobUrl") or item.get("applyUrl") or ""
        if not apply:
            continue
        out.append(
            {
                "company": company,
                "exact_role_title": title,
                "location": str(loc),
                "term": "Winter 2027",
                "official_url": apply,
                "posting_date": (item.get("publishedAt") or "")[:10] or None,
                "notes": f"extra_ats ashby:{token}",
            }
        )
    return out


def scan_extra_ats(cfg: dict) -> list[dict]:
    companies = _load_yaml(COMPANIES_PATH)
    known = _layer1_tokens(companies)
    jobs: list[dict] = []
    with httpx.Client(timeout=30, follow_redirects=True, headers={"User-Agent": USER_AGENT}) as client:
        for entry in cfg.get("extra_ats") or []:
            token = (entry.get("token") or "").strip().lower()
            name = entry.get("name") or token
            ats = (entry.get("ats") or "").lower()
            if not token:
                continue
            if token in known or name.strip().lower().replace(" ", "") in known:
                print(f"skip {name} (already Layer 1)")
                continue
            try:
                if ats == "greenhouse":
                    found = from_greenhouse(client, token, name)
                elif ats == "ashby":
                    found = from_ashby(client, token, name)
                else:
                    print(f"skip {name}: unsupported ats={ats}")
                    continue
                if found:
                    print(f"{ats}/{token}: {len(found)}")
                jobs.extend(found)
            except Exception as exc:
                print(f"FAIL {ats}/{token}: {exc}")
    return jobs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Layer 2 search pack (+ optional extra ATS)")
    parser.add_argument(
        "--scan-extra-ats",
        action="store_true",
        help="Also scan discovery_queries.yml extra_ats boards not in companies.yml",
    )
    args = parser.parse_args(argv)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cfg = _load_yaml(QUERIES_PATH)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

    pack = write_search_pack(cfg, ts)
    print(f"Wrote search pack → {pack}")

    if not args.scan_extra_ats:
        print("Tip: Cursor agent should browse the pack URLs per docs/DISCOVERY_WORKFLOW.md")
        return 0

    unique = []
    seen: set[tuple] = set()
    for j in scan_extra_ats(cfg):
        key = (
            (j.get("company") or "").lower(),
            (j.get("exact_role_title") or "").lower(),
            j.get("official_url") or "",
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(j)

    if not unique:
        print("No extra-ATS winter hits")
        return 0

    path = OUT_DIR / f"{ts}.json"
    payload = {
        "source": "Cursor Agent Monitor",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "discovery": "scripts/agent_discover.py --scan-extra-ats",
        "jobs": unique,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {len(unique)} findings → {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
