#!/usr/bin/env python3
"""
Layer 2 helper — search-pack generator (not a GitHub list scraper).

Default: emit data/agent_findings/_search_pack_<ts>.md with ready-to-open
LinkedIn / Indeed / Handshake / Google URLs from data/discovery_queries.yml.

Optional: --scan-extra-ats probes boards listed under extra_ats that are NOT
already in data/companies.yml (Layer 1). Never fetches Simplify/GitHub lists.

Cursor agents should follow docs/DISCOVERY_WORKFLOW.md, browse those URLs,
resolve official apply links, and write data/agent_findings/<ts>.json.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote_plus

import httpx
import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

QUERIES_PATH = ROOT / "data" / "discovery_queries.yml"
COMPANIES_PATH = ROOT / "data" / "companies.yml"
OUT_DIR = ROOT / "data" / "agent_findings"
USER_AGENT = "W27-SWE-Internships/1.0 (+agent-discover)"

WINTER_RE = re.compile(
    r"winter\s*2027|spring\s*2027|jan(?:uary)?\s*2027|"
    r"jan(?:uary)?\s*[-–/]\s*(?:apr(?:il)?|may)\s*2027",
    re.I,
)
INTERN_RE = re.compile(r"\b(intern|co-?op|co op)\b", re.I)
SWE_RE = re.compile(
    r"software|engineer|developer|full.?stack|backend|frontend|platform|"
    r"infra|swe|devops|sre|machine learning|ml engineer|data engineer",
    re.I,
)


def _load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _layer1_tokens(companies: dict) -> set[str]:
    tokens: set[str] = set()
    for c in companies.get("companies") or []:
        url = (c.get("board_url") or "").rstrip("/")
        if "/boards/" in url and "/jobs" in url:
            # .../boards/{token}/jobs
            parts = url.split("/")
            try:
                i = parts.index("boards")
                tokens.add(parts[i + 1].lower())
            except (ValueError, IndexError):
                pass
        elif "ashbyhq.com/posting-api/job-board/" in url:
            tokens.add(url.split("job-board/")[-1].split("?")[0].lower())
        elif "api.lever.co/v0/postings/" in url:
            tokens.add(url.split("postings/")[-1].split("?")[0].lower())
        name = (c.get("name") or "").strip().lower()
        if name:
            tokens.add(name.replace(" ", ""))
    return tokens


def write_search_pack(cfg: dict, ts: str) -> Path:
    queries = cfg.get("queries") or []
    templates = cfg.get("search_url_templates") or {}
    lines = [
        f"# W27 discovery search pack ({ts})",
        "",
        "Generated by `scripts/agent_discover.py`. Follow `docs/DISCOVERY_WORKFLOW.md`.",
        "",
        "- Use these links for **discovery only**.",
        "- Open the **official apply** page (Greenhouse / Lever / Ashby / Workday / Rippling).",
        "- Do **not** store LinkedIn/Indeed/Handshake URLs as `official_url`.",
        "- Write findings to `data/agent_findings/<timestamp>.json`, then ingest.",
        "",
    ]
    for q in queries:
        lines.append(f"## {q}")
        lines.append("")
        encoded = quote_plus(q)
        for name, tmpl in templates.items():
            url = tmpl.replace("{q}", encoded)
            lines.append(f"- **{name}**: {url}")
        lines.append("")

    path = OUT_DIR / f"_search_pack_{ts}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _winter_blob(*parts: str) -> bool:
    return bool(WINTER_RE.search(" ".join(parts)))


def from_greenhouse(client: httpx.Client, token: str, company: str) -> list[dict]:
    url = f"https://boards-api.greenhouse.io/v1/boards/{token}/jobs"
    data = client.get(url).json()
    out = []
    for item in data.get("jobs") or []:
        title = item.get("title") or ""
        loc = (item.get("location") or {}).get("name") or ""
        if not INTERN_RE.search(title) or not SWE_RE.search(title):
            continue
        if not _winter_blob(title, loc):
            continue
        apply = item.get("absolute_url") or ""
        if not apply:
            continue
        out.append(
            {
                "company": company,
                "exact_role_title": title,
                "location": loc,
                "term": "Winter 2027",
                "official_url": apply,
                "posting_date": None,
                "notes": f"extra_ats greenhouse:{token}",
            }
        )
    return out


def from_ashby(client: httpx.Client, token: str, company: str) -> list[dict]:
    url = f"https://api.ashbyhq.com/posting-api/job-board/{token}"
    resp = client.get(url)
    if resp.status_code != 200:
        return []
    out = []
    for item in resp.json().get("jobs") or []:
        title = item.get("title") or ""
        loc = item.get("location") or ""
        if isinstance(loc, dict):
            loc = loc.get("name") or ""
        desc = (item.get("descriptionPlain") or "")[:4000]
        if not INTERN_RE.search(title):
            continue
        if not SWE_RE.search(f"{title} {desc}"):
            continue
        if not _winter_blob(title, str(loc), desc):
            continue
        apply = item.get("jobUrl") or item.get("applyUrl") or ""
        if not apply:
            continue
        out.append(
            {
                "company": company,
                "exact_role_title": title,
                "location": str(loc),
                "term": "Winter 2027",
                "official_url": apply,
                "posting_date": (item.get("publishedAt") or "")[:10] or None,
                "notes": f"extra_ats ashby:{token}",
            }
        )
    return out


def scan_extra_ats(cfg: dict) -> list[dict]:
    companies = _load_yaml(COMPANIES_PATH)
    known = _layer1_tokens(companies)
    jobs: list[dict] = []
    with httpx.Client(timeout=30, follow_redirects=True, headers={"User-Agent": USER_AGENT}) as client:
        for entry in cfg.get("extra_ats") or []:
            token = (entry.get("token") or "").strip().lower()
            name = entry.get("name") or token
            ats = (entry.get("ats") or "").lower()
            if not token:
                continue
            if token in known or name.strip().lower().replace(" ", "") in known:
                print(f"skip {name} (already Layer 1)")
                continue
            try:
                if ats == "greenhouse":
                    found = from_greenhouse(client, token, name)
                elif ats == "ashby":
                    found = from_ashby(client, token, name)
                else:
                    print(f"skip {name}: unsupported ats={ats}")
                    continue
                if found:
                    print(f"{ats}/{token}: {len(found)}")
                jobs.extend(found)
            except Exception as exc:
                print(f"FAIL {ats}/{token}: {exc}")
    return jobs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Layer 2 search pack (+ optional extra ATS)")
    parser.add_argument(
        "--scan-extra-ats",
        action="store_true",
        help="Also scan discovery_queries.yml extra_ats boards not in companies.yml",
    )
    args = parser.parse_args(argv)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cfg = _load_yaml(QUERIES_PATH)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

    pack = write_search_pack(cfg, ts)
    print(f"Wrote search pack → {pack}")

    if not args.scan_extra_ats:
        print("Tip: Cursor agent should browse the pack URLs per docs/DISCOVERY_WORKFLOW.md")
        return 0

    unique = []
    seen: set[tuple] = set()
    for j in scan_extra_ats(cfg):
        key = (
            (j.get("company") or "").lower(),
            (j.get("exact_role_title") or "").lower(),
            j.get("official_url") or "",
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(j)

    if not unique:
        print("No extra-ATS winter hits")
        return 0

    path = OUT_DIR / f"{ts}.json"
    payload = {
        "source": "Cursor Agent Monitor",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "discovery": "scripts/agent_discover.py --scan-extra-ats",
        "jobs": unique,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {len(unique)} findings → {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
